version: '3.8'

services:
  comparator-app:
    build: .
    container_name: python_data_comparator
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: always